### ISSUE TITLE
What about fullscreen?

### ISSUE THREAD

**Issue by bernardoadc** [amercier/ng-media-events#3]
Will it be supported? I realize that is tricky still today, but even more desirable to be in a lib. (not sure but I think videogular supports this).

**Comment by amercier** [comment]
Hi, what do you mean by "supporting fullscreen"? This project is about [Media events](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events).

You may want to combine this with some fullscreen-specific Angular directive.

**Comment by bernardoadc** [comment]
Oh, ok.. I thought it would support every event that involved a video tag, for example. To avoid things like this: https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API#Prefixing. But now I see that altough we can call `Element.requestFullscreen()` the `onfullscreenchange` event will be bound to the whole `document`.

So in the end is a matter of web standard definition. Thanks

**Comment by amercier** [comment]
Yes, I try to keep this package minimal, so it only focuses on media events and stay as lightweight as possible. There might be some good modules for doing fullscreen out there, such as [hrajchert/angular-screenfull](https://github.com/hrajchert/angular-screenfull) or [fabiobiondi/angular-fullscreen](https://github.com/fabiobiondi/angular-fullscreen), but I haven't tested them.

(sorry for the possibly rude tone on my first message, it wasn't intentional)

**Comment by bernardoadc** [comment]
Nice, thanks for the tips! No worries, didn't sound rude to me at all
Keep up the good work!
